---
title: "EDA"
author: "Jorge Navarro Garcia"
date: "13 de marzo de 2017"
output: html_document
---

# Librerías

```{r}
library(magrittr)
library(dplyr)
library(ggplot2)
library(lubridate)
```

# Carga de datos del Proyecto

```{r}
if(!file.exists("./data/2014.csv")) {
  download.file("http://www.nyc.gov/html/nypd/downloads/zip/analysis_and_planning/2014_sqf_csv.zip",
    "2014_sqf_csv")
  unzip("2014_sqf_csv")
}

SQFdata <- read.csv("./data/2014.csv")

dim(SQFdata)
```

# Limpieza de datos

```{r}
SQFdata$datestop
source('./code/Cleaning_Data.r')
SQFdata$datestop
```

# Descarga de nuevos datos para raza

```{r}
if(!file.exists("./data/2010.csv")) {
  download.file("http://www.nyc.gov/html/nypd/downloads/zip/analysis_and_planning/2010_sqf_csv.zip",
    "2010_sqf_csv")
  unzip("2010_sqf_csv",exdir = './data/')
}
if(!file.exists("./data/2011.csv")) {
  download.file("http://www.nyc.gov/html/nypd/downloads/zip/analysis_and_planning/2011_sqf_csv.zip",
    "2011_sqf_csv")
  unzip("2011_sqf_csv",exdir = './data/')
}
if(!file.exists("./data/2012.csv")) {
  download.file("http://www.nyc.gov/html/nypd/downloads/zip/analysis_and_planning/2012_sqf_csv.zip",
    "2012_sqf_csv")
  unzip("2012_sqf_csv",exdir = './data/')
}
if(!file.exists("./data/2013.csv")) {
  download.file("http://www.nyc.gov/html/nypd/downloads/zip/analysis_and_planning/2013_sqf_csv.zip",
    "2013_sqf_csv")
  unzip("2013_sqf_csv",exdir = './data/')
}

SQFdata10 <- read.csv("./data/2010.csv")
SQFdata11 <- read.csv("./data/2011.csv")
SQFdata12 <- read.csv("./data/2012.csv")
SQFdata13 <- read.csv("./data/2013.csv")

SQFdata10$perstop = as.integer(SQFdata10$perstop)
SQFdata11$perstop = as.integer(SQFdata11$perstop)
SQFdata12$perstop = as.integer(SQFdata12$perstop)
SQFdata13$perstop = as.integer(SQFdata13$perstop)

dim(SQFdata10)
dim(SQFdata11)
dim(SQFdata12)
dim(SQFdata13)

SQFdata_race <- merge(SQFdata10,SQFdata11, all = TRUE)
SQFdata_race <- merge(SQFdata_race,SQFdata12, all = TRUE)
SQFdata_race <- merge(SQFdata_race,SQFdata13, all = TRUE)

rm(SQFdata10)
rm(SQFdata11)
rm(SQFdata12)
rm(SQFdata13)

dim(SQFdata_race)

levels(SQFdata_race$race) <- c('ASIAN/PACIFIC ISLANDER','BLACK',
                          'AMERICAN INDIAN/ALASKAN NATIVE',
                          'BLACK-HISPANIC','WHITE-HISPANIC',
                          'WHITE','UNKNOWN','OTHER')

SQFdata_race %>% group_by(race) %>%
    summarise(n())
```

# Análisis de variables: Variables respuesta *perstop* y *arstmade*

```{r race}

# arstmade ~ race
levels(SQFdata$race) <- c('ASIAN','BLACK',
                          'INDIAN',
                          'BLACK-HISP','WHITE-HISP',
                          'WHITE','UNKNOWN','OTHER')

summary(SQFdata$race)

SQFdata %>% group_by(race) %>%
    summarise(count=n()) %>%
    arrange(desc(count))

SQFdata %>% group_by(race) %>%
    filter(arstmade == 'Y') %>%
    summarise(count = n()) %>%
    arrange(desc(count))



tot_cases <- dim(SQFdata)[1]


df <- data.frame(
    race = levels(SQFdata$race),
    cases = (SQFdata %>% group_by(race) %>% summarise(count = n()))$count,
    percent_total = (SQFdata %>% group_by(race) %>% summarise(count = (n())))$count,    
    cases_arrested = (SQFdata %>% group_by(race) %>%
                    filter(arstmade == 'Y') %>%
                    summarise(count = n()))$count,
    percent_arrested = (SQFdata %>% group_by(race) %>% filter(arstmade == 'Y') %>% summarise(count = (n())))$count
)

df$percent_total <- sapply(df$percent_total, function(x){round(x*100/tot_cases,2)})
df <- df %>% mutate(percent_arrested = round(percent_arrested*100/cases,2))
df

# PLOTEAR POR RAZAS LOS ARRESTOS
# SQFdata %>% ggplot() +
#     geom_bar(aes(arstmade)) +
#     facet_wrap(SQFdata$race, nrow = 3)
# 
# 
# df %>% ggplot() +
#     geom_histogram(aes(x=race,y=cases_arrested))
#     geom_hist(aes(x=race,y=cases_arrested)) +
#     facet_wrap(df$race)

# perstop ~ race

myfunc <- function(x){
    x <- round((x)/100,1)*100
    if(x==0){x<-5}
    return(x)
}

SQFdata$perstop <- sapply(SQFdata$perstop,myfunc)


SQFdata %>% 
    group_by(perstop,race) %>%
    summarise(count = n()) %>%
    arrange(desc(perstop))

# OJO -> Al haber modificado los datos para agrupar mejor, INDIAN ha bajado considerablemente su mediana...
SQFdata %>% ggplot() +
    geom_boxplot(aes(x=race,y=perstop)) +
    theme_minimal()

# Subida considerable de la mediana para BLACK -> Meter más datos

```

```{r age}
summary(SQFdata$age)

# arstmade ~ age

hist(SQFdata$age)

SQFdata %>% group_by(age) %>%
    summarise(count = n()) %>%
    arrange(desc(age))

SQFdata$age[which(SQFdata$age < 10 | SQFdata$age > 90)] <- NA

SQFdata %>% group_by(age) %>%
    filter(arstmade == 'Y') %>%
    summarise(count = n()) %>%
    arrange(desc(count))

hist(SQFdata$age)
hist(SQFdata$age[which(SQFdata$arstmade=='Y')])

summary(SQFdata$age)
summary(SQFdata$age[which(SQFdata$arstmade=='Y')])

# perstop ~ age

myfunc <- function(x){
    x <- round((x)/100,1)*100
    if(x==0){x<-5}
    return(x)
}

SQFdata$perstop <- sapply(SQFdata$perstop,myfunc)


myfunc <- function(x){
    x <- round((x)/100,1)*100
    return(x)
}

# OJO -> Arriesgado hacer transformaciones así...
SQFdata$age <- sapply(SQFdata$age,myfunc)


SQFdata %>% 
    group_by(perstop,age) %>%
    summarise(count = n()) %>%
    arrange(desc(perstop))

hist(SQFdata$age)
hist(SQFdata$age[which(SQFdata$perstop>70)])

# Queda claro que age afecta a ambas var respuesta

```


```{r contrabn}

# arstmade ~ contrabn

df_contr <- SQFdata %>%
    group_by(contrabn, arstmade) %>%
    summarise(count = n()) %>%
    arrange(desc(count))

df_contr

cat('Un',df_contr$count[4]*100/(df_contr$count[4]+df_contr$count[3]),'% de los casos en los que se haya contrabando, no terminan en arresto.')

cat('Es decir, al ser un',df_contr$count[3]*100/(df_contr$count[4]+df_contr$count[3]),'% de los casos de contrabando los que acaban en arresto, es determinante. Sería interesante incluir más variables para terminar de asegurar dicha tendencia, ya que tenemos solo',df_contr$count[4]+df_contr$count[3],'casos.')

# perstop ~ contrabn

hist(SQFdata$perstop[which(SQFdata$contrabn=='Y')])
hist(SQFdata$perstop[which(SQFdata$contrabn=='N')])


SQFdata %>% 
    group_by(perstop,contrabn) %>%
    filter(contrabn == 'Y') %>%
    summarise(count = n()) %>%
    arrange(desc(count))

summary(SQFdata$perstop[which(SQFdata$contrabn == 'Y')])

# Para el caso de perstop, parece haber bastante variación en los casos -> No es interesante

```

```{r asltweap}
# asltweap -> WAS AN ASSAULT WEAPON FOUND ON SUSPECT ?
# 10859 NAs -> Incluir datos de otros años para aumentar información???

# arstmade ~ asltweap

SQFdata %>% group_by(asltweap) %>%
    summarise(n())

# Solo 3 casos -> No es medible, ¿incluir casos de otros años? Seguramente haya pocos casos de gente con rifles de asalto por la calle...

```

```{r detailCM}
# arstmade ~ detailCM
# Crime code description -> En 2014 SQF Codebook, descripción

hist(as.numeric(SQFdata$detailCM))
hist(as.numeric(SQFdata$detailCM[which(SQFdata$arstmade == 'Y')]))

SQFdata %>% group_by(detailCM) %>%
    filter(arstmade == 'Y') %>%
    # mutate(count = n()) %>%
    summarise(count = n()) %>%
    # select(count, arstmade) %>%
    # filter(count>1000) %>%
    arrange(desc(count))


# perstop ~ detailCM

df_detailCM <- SQFdata %>% 
    group_by(detailCM) %>%
    mutate(count = n()) %>%
    filter(count > 900) %>%
    arrange(desc(count))
    
df_detailCM %>% ggplot() +
    geom_boxplot(aes(x = detailCM,y=perstop))

# Muchas diferencias en perstop según el tipo de crimen -> Importante
# Parece que se corresponden los casos de perstop mayor con arstmade == Y


```

```{r pf_grnd}
# pf_grnd -> PHYSICAL FORCE USED BY OFFICER - SUSPECT ON GROUND
# 10742 NAs

SQFdata %>% group_by(pf_grnd) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# Ocurre lo mismo que para asltweap, pocos datos -> ¿UNIR TODAS LAS VARIABLES pf_?
```

```{r pf_drwep}
# pf_drwep
# 10770 NAs

SQFdata %>% group_by(pf_drwep) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# Ocurre lo mismo que para asltweap, pocos datos -> ¿UNIR TODAS LAS VARIABLES pf_?
```

```{r cs_descr}
# cs_descr -> REASON FOR STOP - FITS A RELEVANT DESCRIPTION
# 7509 NAs


# arstmade ~ cs_descr

df_cs_descr <- SQFdata %>%
    group_by(cs_descr, arstmade) %>%
    filter(cs_descr == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_cs_descr

cat('Un',df_cs_descr$count[1]*100/(df_cs_descr$count[2]+df_cs_descr$count[1]),'% de los casos en los que se encaja en una descripción, no terminan en arresto. No parece ser un motivo determinante. El problema es que al haber varias razones de parada, el porcentaje habría que compararlo con el resto de razones...')


# perstop ~ cs_descr

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = cs_descr,y = perstop))

# Aparentemente, si encaja con una descripción tardan menos tiempo en la parada. Puede ser porque se limiten a comprobar la identidad del sospechoso y dejarle marchar.

```

```{r cs_casng}
# cs_casng -> REASON FOR STOP - CASING A VICTIM OR LOCATION -> CASING????
# 8026 NAs

# arstmade ~ cs_casng

df_cs_casng <- SQFdata %>%
    group_by(cs_casng, arstmade) %>%
    filter(cs_casng == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_cs_casng

cat('Un',df_cs_casng$count[1]*100/(df_cs_casng$count[2]+df_cs_casng$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. No parece ser un motivo determinante. El problema es que al haber varias razones de parada, el porcentaje habría que compararlo con el resto de razones...')

# perstop ~ cs_casng

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = cs_casng,y = perstop))

# La mediana en los casos en los que se marca esta razón para la parada es mucho mayor que los casos en los que no. Habría que aclarar qué significa CASING. En cualquier caso, es determinante.

```

```{r cs_other}
# cs_other
# 8065 NAs

# arstmade ~ cs_other

df_cs_other <- SQFdata %>%
    group_by(cs_other, arstmade) %>%
    filter(cs_other == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_cs_other

cat('Un',df_cs_other$count[1]*100/(df_cs_other$count[2]+df_cs_other$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. No parece ser un motivo determinante. El problema es que al haber varias razones de parada, el porcentaje habría que compararlo con el resto de razones...')

# perstop ~ cs_casng

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = cs_other,y = perstop))

# En este caso, las medianas del perstop para ambos casos son más cercanas.
# ¿Es normal que haya tanta variación en la mediana de los N para cada reason? -> ¿Se corregiría cambiando NAs a N?
```

```{r rf_othsw}
# rf_othsw -> REASON FOR FRISK - OTHER SUSPICION OF WEAPONS
# 9776 NAs

# arstmade ~ rf_othsw

df_rf_othsw <- SQFdata %>%
    group_by(rf_othsw, arstmade) %>%
    filter(rf_othsw == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_rf_othsw

cat('Un',df_rf_othsw$count[1]*100/(df_rf_othsw$count[2]+df_rf_othsw$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. Tenemos pocos valores, sería interesante meter más de otros años')

# perstop ~ rf_othsw

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = rf_othsw,y = perstop))

# Parece haber diferencias entre ambos casos, pero sería interesante tener más información.
```

```{r rf_bulg}
# rf_bulg -> REASON FOR FRISK - SUSPICIOUS BULGE
# 10055 NAs

# arstmade ~ rf_bulg

df_rf_bulg <- SQFdata %>%
    group_by(rf_bulg, arstmade) %>%
    filter(rf_bulg == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_rf_bulg

cat('Un',df_rf_bulg$count[1]*100/(df_rf_bulg$count[2]+df_rf_bulg$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. Parece una diferencia grande, pero al igual que en rf_othsw, tenemos pocos valores y sería interesante meter más de otros años')

# perstop ~ rf_bulg

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = rf_bulg,y = perstop))

# Parece NO haber grandes diferencias entre ambos casos -> más datos.
```

```{r sb_hdobj}
# sb_hdobj -> BASIS OF SEARCH - HARD OBJECT
# 10083 NAs

# arstmade ~ sb_hdobj

df_sb_hdobj <- SQFdata %>%
    group_by(sb_hdobj, arstmade) %>%
    filter(sb_hdobj == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_sb_hdobj

cat('Un',df_sb_hdobj$count[1]*100/(df_sb_hdobj$count[2]+df_sb_hdobj$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. Igual que en rf_othsw, tenemos pocos valores y sería interesante meter más de otros años')

# perstop ~ sb_hdobj

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = sb_hdobj,y = perstop))

# Parece NO haber grandes diferencias entre ambos casos -> más datos.
```

```{r ac_cgdir}
# ac_cgdir -> ADDITIONAL CIRCUMSTANCES - CHANGE DIRECTION AT SIGHT OF OFFICER
# 8043 NAs

# arstmade ~ ac_cgdir

df_ac_cgdir <- SQFdata %>%
    group_by(ac_cgdir, arstmade) %>%
    filter(ac_cgdir == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_ac_cgdir

cat('Un',df_ac_cgdir$count[1]*100/(df_ac_cgdir$count[2]+df_ac_cgdir$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. La diferencia parece ser grande, se podría decir que no es determinante. Meter más datos para confirmar.')
    
# perstop ~ ac_cgdir

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = ac_cgdir,y = perstop))

# Parece NO haber grandes diferencias entre ambos casos -> más datos.
```

```{r ac_incid}
# ac_incid -> ADDITIONAL CIRCUMSTANCES - AREA HAS HIGH CRIME INCIDENCE
# 5223 NAs

# arstmade ~ ac_incid

df_ac_incid <- SQFdata %>%
    group_by(ac_incid, arstmade) %>%
    filter(ac_incid == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_ac_incid

cat('Un',df_ac_incid$count[1]*100/(df_ac_incid$count[2]+df_ac_incid$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. Se trata de una gran diferencia, no es determinante para el arresto.')

# perstop ~ ac_incid

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = ac_incid,y = perstop))

# La mediana en los casos en los que se marca esta razón es algo mayor que en el resto. ¿Incluir más datos?
```

```{r ac_other}
# ac_other -> ADDITIONAL CIRCUMSTANCES - OTHER
# 10095

# arstmade ~ ac_other

df_ac_other <- SQFdata %>%
    group_by(ac_other, arstmade) %>%
    filter(ac_other == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_ac_other

cat('Un',df_ac_other$count[1]*100/(df_ac_other$count[2]+df_ac_other$count[1]),'% de los casos en los que se marca esta razón para la parada, no terminan en arresto. No son suficientes datos.')

# perstop ~ ac_other

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = ac_other,y = perstop))

# Parecen presentarse tiempos menores en caso de que esta variable sea Y. Incluir más datos.
# Si bien, también es cierto que no es una variable que aclare o aporte información -> OTHER CIRCUMSTANCES...
```

```{r stinter}
# stinter
# String -> location of stopo intersection -> Es interesante?

# arstmade ~ stinter
SQFdata %>% group_by(stinter) %>%
    filter(arstmade == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

# Muy pocos datos... ¿Utilidad?

# perstop ~ stinter
df_stinter <- SQFdata %>% 
    group_by(stinter) %>%
    mutate(count = n()) %>%
    filter(count > 300) %>%
    # select(perstop, count) %>%
    arrange(desc(count))

df_stinter %>% ggplot() +
    geom_boxplot(aes(x = stinter,y=perstop))

# Pocos datos para asegurar nada...
```

```{r sector}
# sector
# location of stop sector -> 1 a 21 según Codebook


#arstmade ~ sector
hist(as.numeric(SQFdata$sector))
hist(as.numeric(SQFdata$sector[which(SQFdata$arstmade == 'Y')]))

SQFdata %>% group_by(sector) %>%
    filter(arstmade == 'Y') %>%
    summarise(count = n()) %>%
    arrange(desc(count))

# Habría que ver a qué hacen referencia los sectores -> ¿Zonas de la ciudad? En principio parece relevante si es alguno de los primeros. Faltarían más datos.

# perstop ~ sector

df_sector <- SQFdata %>% 
    group_by(sector) %>%
    mutate(count = n()) %>%
    # filter(count > 900) %>%
    arrange(desc(count))

df_sector %>% ggplot() +
    geom_boxplot(aes(x = sector,y=perstop))

# Parece haber algunas diferencias entre algunos sectores como  (C, D) y (T, U). También aparece M, pero con 173 casos sólo no es claro si es determinante o anecdótico. MÁS DATOS.
```

```{r typeofid}
# typeofid -> STOPPED PERSON'S IDENTIFICATION TYPE
# 

levels(SQFdata$typeofid) <- c('OTHER','PHOTO','REFUSED','VERBAL')

#arstmade ~ typeofid
hist(as.numeric(SQFdata$typeofid))
hist(as.numeric(SQFdata$typeofid[which(SQFdata$arstmade == 'Y')]))

# En el histograma aparecen muchos más casos de arresto cuando se da identificación por foto, pero es que en general hay muchos más casos para ese tipo de identificación.

SQFdata %>% group_by(typeofid) %>%
    filter(arstmade == 'Y') %>%
    summarise(count = n()) %>%
    arrange(desc(count))

SQFdata %>% group_by(typeofid, arstmade) %>%
    summarise(count = n()) %>%
    arrange(arstmade)

# Habría que ver a qué hacen referencia los sectores -> ¿Zonas de la ciudad? En principio parece relevante si es alguno de los primeros. Faltarían más datos.

# perstop ~ typeofid

df_typeofid <- SQFdata %>% 
    group_by(typeofid) %>%
    mutate(count = n()) %>%
    # filter(count > 900) %>%
    arrange(desc(count))

df_typeofid %>% ggplot() +
    geom_boxplot(aes(x = typeofid,y=perstop))

# No parece haber grandes diferencias entre unos y otros en cuanto a cuartiles. Sin embargo la mediana parece variar algo más. Sería interesante meter más datos.
```

```{r othpers}
# othpers -> WERE OTHER PERSONS STOPPED, QUESTIONED OR FRISKED ?
# 

# arstmade ~ othpers

df_othpers <- SQFdata %>%
    group_by(othpers, arstmade) %>%
    filter(othpers == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_othpers

cat('Un',df_othpers$count[1]*100/(df_othpers$count[2]+df_othpers$count[1]),'% de los casos en los que se para, se cuestiona o se cachea a otras personas, no terminan en arresto. No es determinante, lo cual tiene sentido porque deberían ser independientes el arresto con el número de personas implicadas.')

# perstop ~ othpers

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = othpers,y = perstop))

# Parecen presentarse tiempos menores en caso de que esta variable sea Y. Podría tener sentido al tener que 'repartir' el tiempo los agentes entre varias personas (¿¿??).
```

```{r radio}
# radio -> RADIO RUN
#

# arstmade ~ radio

df_radio <- SQFdata %>%
    group_by(radio, arstmade) %>%
    filter(radio == 'Y') %>%
    summarise(count=n())%>%
    arrange(desc(count))

df_radio

cat('Un',df_radio$count[1]*100/(df_radio$count[2]+df_radio$count[1]),'% de los casos en los que se ¿da aviso por radio?, no terminan en arresto. No es determinante.')

# perstop ~ radio

SQFdata %>% ggplot() +
    geom_boxplot(aes(x = radio,y = perstop))

# Parecen presentarse tiempos menores en caso de que esta variable sea Y. ¿Sentido? -> No es determinante

```
