---
title: "EDA"
author: "Jorge Navarro Garcia"
date: "13 de marzo de 2017"
output: html_document
---

# Reparto de variables

```{r Nathaly}

# pct
# precint of stop 1 through 123

SQFdata %>% group_by(pct) %>%
    summarise(count=n()) %>%
    arrange(desc(count))

# ser_num
# UF-250 serial number

SQFdata %>% group_by(ser_num) %>%
    summarise(count=n()) %>%
    arrange(desc(count))

SQFdata$ser_num[which(is.na(SQFdata$ser_num))]

# city
# Condados

SQFdata %>% group_by(city) %>%
    summarise(count=n()) %>%
    arrange(desc(count))

SQFdata$city[which(is.na(SQFdata$city))]

# searched
# 

SQFdata %>% group_by(searched) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$searched[which(is.na(SQFdata$searched))]

# pistol
# 10806 NAs...

SQFdata %>% group_by(pistol) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# perobs
# 

SQFdata %>% group_by(perobs) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$perobs[which(is.na(SQFdata$perobs))]

# pf_hcuff
# 9714

SQFdata %>% group_by(pf_hcuff) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# pf_pepsp
# 10857 NAs

SQFdata %>% group_by(pf_pepsp) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_drgtr
# 10037 NAs

SQFdata %>% group_by(cs_drgtr) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_furtv
# 6479 NAs

SQFdata %>% group_by(cs_furtv) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_vcrim
# 9709 NAs

SQFdata %>% group_by(cs_vcrim) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_rfcmp
# 9475 NAs

SQFdata %>% group_by(rf_rfcmp) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_verbl
# 10741 NAs

SQFdata %>% group_by(rf_verbl) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# sb_other
# 9981 NAs

SQFdata %>% group_by(sb_other) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_proxm
# 7566 NAs

SQFdata %>% group_by(ac_proxm) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_rept
# 8272 NAs

SQFdata %>% group_by(ac_rept) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# inout
# 

SQFdata %>% group_by(inout) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$inout[which(is.na(SQFdata$inout))]

# trhsloc
# 

SQFdata %>% group_by(trhsloc) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$trhsloc[which(is.na(SQFdata$trhsloc))]

# addrpct
# location of address precinct -> Es interesante?

SQFdata %>% group_by(addrpct) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$addrpct[which(is.na(SQFdata$addrpct))]

# repcmd
# reporting officer's command -> Es interesante?

SQFdata %>% group_by(repcmd) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$repcmd[which(is.na(SQFdata$repcmd))]

# revcmd
# reviewing officer's command -> Es interesante?

SQFdata %>% group_by(revcmd) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$revcmd[which(is.na(SQFdata$revcmd))]

```


```{r Hugo}

# sex

SQFdata %>% group_by(sex) %>%
    summarise(count=n()) %>%
    arrange(desc(count))

SQFdata$sex[which(is.na(SQFdata$sex))]

# weight
# Weight in pounds

SQFdata %>% group_by(weight) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$weight[which(is.na(SQFdata$weight))]

# haircolr
# 

SQFdata %>% group_by(haircolr) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$haircolr[which(is.na(SQFdata$haircolr))]

# riflshot
# 10860 NAs

SQFdata %>% group_by(riflshot) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# sumissue
# Was summons issued?

SQFdata %>% group_by(sumissue) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$sumissue[which(is.na(SQFdata$sumissue))]

# pf_hands
# 9133 NAs

SQFdata %>% group_by(pf_hands) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# pf_wall
# 10412 NAs

SQFdata %>% group_by(pf_wall) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# pf_other
# 10813 NAs

SQFdata %>% group_by(pf_other) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_objcs
# 10445 NAs

SQFdata %>% group_by(cs_objcs) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_bulge
# 10032 NAs

SQFdata %>% group_by(cs_bulge) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_vcrim
# 8325 NAs

SQFdata %>% group_by(rf_vcrim) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_knowl
# 10244 NAs

SQFdata %>% group_by(rf_knowl) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_furt
# 6880 NAs

SQFdata %>% group_by(rf_furt) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_evasv
# 8553 NAs

SQFdata %>% group_by(ac_evasv) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_assoc
# 9972 NAs

SQFdata %>% group_by(ac_assoc) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_inves
# 9355 NAs

SQFdata %>% group_by(ac_inves) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# stname
# String -> location of stop street name -> Es interesante?

SQFdata %>% group_by(stname) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$stname[which(is.na(SQFdata$stname))]

# offunif
# 

SQFdata %>% group_by(offunif) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$offunif[which(is.na(SQFdata$offunif))]

# offverb
# verbal statement provided by officer (if not in uniform) -> Limpiar datos

SQFdata %>% group_by(offverb) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$offverb[which(is.na(SQFdata$offverb))]

# officrid
# id card provided by officer (if not in uniform) -> Limpiar datos

SQFdata %>% group_by(officrid) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$officrid[which(is.na(SQFdata$officrid))]

# offshld
# shield provided by officer (if not in uniform) -> Limpiar datos

SQFdata %>% group_by(offshld) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$offshld[which(is.na(SQFdata$offshld))]

```


```{r Jorge}

# race

SQFdata$race

SQFdata %>% group_by(race) %>%
    summarise(count=n()) %>%
    arrange(desc(count))

SQFdata$race[which(is.na(SQFdata$race))]

# age

SQFdata %>% group_by(age) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata %>% group_by(age) %>%
    summarise(count = n()) %>%
    arrange(desc(as.numeric(age)))

summary(as.numeric(SQFdata$age))

SQFdata$age[which(is.na(SQFdata$age))]

# contrabn
# 

SQFdata %>% group_by(contrabn) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$contrabn[which(is.na(SQFdata$contrabn))]

# asltweap
# 10859 NAs

SQFdata %>% group_by(asltweap) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# detailCM
# Crime code description -> En 2014 SQF Codebook, descripción

SQFdata %>% group_by(detailCM) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$detailCM[which(is.na(SQFdata$detailCM))]

# pf_grnd
# 10742 NAs

SQFdata %>% group_by(pf_grnd) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# pf_drwep
# 10770 NAs

SQFdata %>% group_by(pf_drwep) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_descr
# 7509 NAs

SQFdata %>% group_by(cs_descr) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_casng
# 8026 NAs

SQFdata %>% group_by(cs_casng) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_other
# 8065 NAs

SQFdata %>% group_by(cs_other) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_othsw
# 9776 NAs

SQFdata %>% group_by(rf_othsw) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_bulg
# 10055 NAs

SQFdata %>% group_by(rf_bulg) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# sb_hdobj
# 10083 NAs

SQFdata %>% group_by(sb_hdobj) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_cgdir
# 8043 NAs

SQFdata %>% group_by(ac_cgdir) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_incid
# 5223 NAs

SQFdata %>% group_by(ac_incid) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_other
# 10095

SQFdata %>% group_by(ac_other) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# stinter
# String -> location of stopo intersection -> Es interesante?

SQFdata %>% group_by(stinter) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$stinter[which(is.na(SQFdata$stinter))]

# sector
# location of stop sector -> 1 a 21 según Codebook

SQFdata %>% group_by(sector) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$sector[which(is.na(SQFdata$sector))]

# typeofid
# 

SQFdata %>% group_by(typeofid) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$typeofid[which(is.na(SQFdata$typeofid))]

# othpers
# 

SQFdata %>% group_by(othpers) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$othpers[which(is.na(SQFdata$othpers))]

# radio
# radio run

SQFdata %>% group_by(radio) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$radio[which(is.na(SQFdata$radio))]

```


```{r Iván}

# build
# 

SQFdata %>% group_by(build) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$build[which(is.na(SQFdata$build))]

# frisked
# 

SQFdata %>% group_by(frisked) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$frisked[which(is.na(SQFdata$frisked))]

# knifcuti
# 10605 NAs

SQFdata %>% group_by(knifcuti) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# machgun
# 10860 NAs? -> Ningún valor Y

SQFdata %>% group_by(machgun) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# othrweap
# 10771 NAs

SQFdata %>% group_by(othrweap) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# pf_ptwep
# 10780

SQFdata %>% group_by(pf_ptwep) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# pf_baton
# 10856 NAs

SQFdata %>% group_by(pf_baton) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_lkout
# 9348 NAs

SQFdata %>% group_by(cs_lkout) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# cs_cloth
# 10431 NAs

SQFdata %>% group_by(cs_cloth) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_attir
# 10178 NAs

SQFdata %>% group_by(rf_attir) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# rf_vcact
# 9894 NAs

SQFdata %>% group_by(rf_vcact) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# sb_outln
# 10761 NAs

SQFdata %>% group_by(sb_outln) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# sb_admis
# 10771 NAs

SQFdata %>% group_by(sb_admis) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_time
# 6807 NAs

SQFdata %>% group_by(ac_time) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# ac_stsnd
# 10540 NAs

SQFdata %>% group_by(ac_stsnd) %>%
    summarise(count=n())%>%
    arrange(desc(count))

# forceuse
# Reason for force -> Interesante??

SQFdata %>% group_by(forceuse) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$forceuse[which(is.na(SQFdata$forceuse))]

# crossst
# String -> location of stop cross street -> Es interesante?

SQFdata %>% group_by(crossst) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$crossst[which(is.na(SQFdata$crossst))]

# xcoord
# 

SQFdata %>% group_by(xcoord) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$xcoord[which(is.na(SQFdata$xcoord))]

# ycoord
# 

SQFdata %>% group_by(ycoord) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$ycoord[which(is.na(SQFdata$ycoord))]

# explnstp
# did officer explain reason for stop? -> Sólo 68 N -> Es interesante?

SQFdata %>% group_by(explnstp) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$explnstp[which(is.na(SQFdata$explnstp))]

```


```{r Deshechadas}

# year
# No aplica

# datestop
# No aplica

# timestop
# No aplica

# dob
# No aplica

# height
# Aparentemente no existe
SQFdata %>% group_by(height) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$height[which(is.na(SQFdata$height))]

# othfeatr
# Demasiados NA -> No es interesante

SQFdata %>% group_by(othfeatr) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$othfeatr[which(is.na(SQFdata$othfeatr))]

# arstoffn
# String -> offense suspect arrested for -> No es interesante

SQFdata %>% group_by(arstoffn) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$arstoffn[which(is.na(SQFdata$arstoffn))]

# sumoffen
# String -> offense suspect was summonsed for -> No es interesante

SQFdata %>% group_by(sumoffen) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$sumoffen[which(is.na(SQFdata$sumoffen))]

# crimsusp
# String -> crime suspected -> No es interesante

SQFdata %>% group_by(crimsusp) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$crimsusp[which(is.na(SQFdata$crimsusp))]

# premname
# String -> location of stop premise name -> No es interesante

SQFdata %>% group_by(premname) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$premname[which(is.na(SQFdata$premname))]

# addrnum
# location of stop address number -> No es interesante

SQFdata %>% group_by(addrnum) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$addrnum[which(is.na(SQFdata$addrnum))]

# beat
# location of stop beat -> 32141 NAs -> No es interesante

SQFdata %>% group_by(beat) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$beat[which(is.na(SQFdata$beat))]

# post
# 41852 NAs -> No es interesante

SQFdata %>% group_by(post) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$post[which(is.na(SQFdata$post))]

# recstat
# record status -> No es interesante

SQFdata %>% group_by(recstat) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$recstat[which(is.na(SQFdata$recstat))]

# linecm
# count > 1 additional details -> No es interesante

SQFdata %>% group_by(lineCM) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$lineCM[which(is.na(SQFdata$lineCM))]

```


```{r Variables respuesta}

# perstop
# Variable respuesta

SQFdata %>% group_by(searched) %>%
    summarise(count=n())%>%
    arrange(desc(count))

SQFdata$searched[which(is.na(SQFdata$searched))]

# arstmade
# Variable respuesta

SQFdata %>% group_by(arstmade) %>%
    summarise(count=n())%>%
    arrange(desc(count))
```