---
title: "hfernandez_SVM"
author: "Hugo Fernandez"
date: "3 de julio de 2017"
output: html_document
---

```{r, message=FALSE}
# Carga de librerías
library(magrittr)
library(dplyr)
library(caret)
library(cluster)
library(useful)
library(NbClust)
library(e1071)
```

## Carga de datos

```{r,message=FALSE}
# Carga del Dataset
if (!grepl('code', getwd())) setwd('./code')
source('OLD/Cleaning_Data.R')
dim(SQFdata)
```

## 3.3 Transformación de variables

### 3.3.1 Creación de dataset transformado

```{r}
SQFdata_modif <- SQFdata
```

### 3.3.2 Eliminación de variables

```{r}
#
# Eliminación de variables con más de ~60% de datos faltantes.
#
SQFdata_modif <- SQFdata_modif %>%
                    select(-c(arstoffn, sumoffen, officrid, offverb, offshld,
                              forceuse, othfeatr, addrnum, stname, beat,
                              post, state, zip, rescode, premtype, aptnum))


#
# Eliminación de variables con poca o nula varianza (casos pertenecientes
# todos a una misma clase). 7 variables eliminadas
#
SQFdata_modif <- SQFdata_modif %>%
                    select(-c(adtlrept, riflshot, asltweap, machgun,
                             pf_baton, pf_pepsp, addrtyp, year,
                             compyear, comppct, lineCM, dob, dettypCM))



# 
# Eliminación de variables con demasiados niveles (strings). 8 variables eliminadas
# 
SQFdata_modif <- SQFdata_modif %>%
                    select(-c(premname, stinter, crossst, sector,
                              pct, crimsusp, addrpct, detailCM))

# 
# Variables asociadas a series temporales o coordenadas -> No son de interés para
# el problema que ocupa
# 
SQFdata_modif <- SQFdata_modif %>%
                    select(-c(datestop, timestop, xcoord, ycoord))



# 
# Número de variables final
# 
dim(SQFdata)
dim(SQFdata_modif)
```

### 3.3.3 Tratamiento de NAs

```{r}
# 
# Eliminación de NAs en variable age
#
SQFdata_modif <- SQFdata_modif %>% filter(!is.na(age))



# 
# Modificación de variables no eliminadas
# 

# Uso de armas
SQFdata_modif$pistol[which(is.na(SQFdata_modif$pistol))]     <- 'N'
SQFdata_modif$knifcuti[which(is.na(SQFdata_modif$knifcuti))] <- 'N'
SQFdata_modif$othrweap[which(is.na(SQFdata_modif$othrweap))] <- 'N'

# Uso de fuerza física
SQFdata_modif$pf_hands[which(is.na(SQFdata_modif$pf_hands))] <- 'N'
SQFdata_modif$pf_wall[which(is.na(SQFdata_modif$pf_wall))]   <- 'N'
SQFdata_modif$pf_grnd[which(is.na(SQFdata_modif$pf_grnd))]   <- 'N'
SQFdata_modif$pf_drwep[which(is.na(SQFdata_modif$pf_drwep))] <- 'N'
SQFdata_modif$pf_ptwep[which(is.na(SQFdata_modif$pf_ptwep))] <- 'N'
SQFdata_modif$pf_hcuff[which(is.na(SQFdata_modif$pf_hcuff))] <- 'N'
SQFdata_modif$pf_other[which(is.na(SQFdata_modif$pf_other))] <- 'N'

# Circunstancias adicionales
SQFdata_modif$ac_rept[which(is.na(SQFdata_modif$ac_rept))]   <- 'N'
SQFdata_modif$ac_inves[which(is.na(SQFdata_modif$ac_inves))] <- 'N'
SQFdata_modif$ac_proxm[which(is.na(SQFdata_modif$ac_proxm))] <- 'N'
SQFdata_modif$ac_incid[which(is.na(SQFdata_modif$ac_incid))] <- 'N'
SQFdata_modif$ac_time[which(is.na(SQFdata_modif$ac_time))]   <- 'N'
SQFdata_modif$ac_evasv[which(is.na(SQFdata_modif$ac_evasv))] <- 'N'
SQFdata_modif$ac_assoc[which(is.na(SQFdata_modif$ac_assoc))] <- 'N'
SQFdata_modif$ac_cgdir[which(is.na(SQFdata_modif$ac_cgdir))] <- 'N'
SQFdata_modif$ac_stsnd[which(is.na(SQFdata_modif$ac_stsnd))] <- 'N'
SQFdata_modif$ac_other[which(is.na(SQFdata_modif$ac_other))] <- 'N'

# Razones para el cacheo
SQFdata_modif$rf_vcrim[which(is.na(SQFdata_modif$rf_vcrim))] <- 'N'
SQFdata_modif$rf_othsw[which(is.na(SQFdata_modif$rf_othsw))] <- 'N'
SQFdata_modif$rf_attir[which(is.na(SQFdata_modif$rf_attir))] <- 'N'
SQFdata_modif$rf_vcact[which(is.na(SQFdata_modif$rf_vcact))] <- 'N'
SQFdata_modif$rf_rfcmp[which(is.na(SQFdata_modif$rf_rfcmp))] <- 'N'
SQFdata_modif$rf_furt[which(is.na(SQFdata_modif$rf_furt))]   <- 'N'
SQFdata_modif$rf_bulg[which(is.na(SQFdata_modif$rf_bulg))]   <- 'N'
SQFdata_modif$rf_verbl[which(is.na(SQFdata_modif$rf_verbl))] <- 'N'
SQFdata_modif$rf_knowl[which(is.na(SQFdata_modif$rf_knowl))] <- 'N'

# Razones para la detención
SQFdata_modif$cs_objcs[which(is.na(SQFdata_modif$cs_objcs))] <- 'N'
SQFdata_modif$cs_descr[which(is.na(SQFdata_modif$cs_descr))] <- 'N'
SQFdata_modif$cs_casng[which(is.na(SQFdata_modif$cs_casng))] <- 'N'
SQFdata_modif$cs_lkout[which(is.na(SQFdata_modif$cs_lkout))] <- 'N'
SQFdata_modif$cs_cloth[which(is.na(SQFdata_modif$cs_cloth))] <- 'N'
SQFdata_modif$cs_drgtr[which(is.na(SQFdata_modif$cs_drgtr))] <- 'N'
SQFdata_modif$cs_furtv[which(is.na(SQFdata_modif$cs_furtv))] <- 'N'
SQFdata_modif$cs_vcrim[which(is.na(SQFdata_modif$cs_vcrim))] <- 'N'
SQFdata_modif$cs_bulge[which(is.na(SQFdata_modif$cs_bulge))] <- 'N'
SQFdata_modif$cs_other[which(is.na(SQFdata_modif$cs_other))] <- 'N'

# Motivos de búsqueda
SQFdata_modif$sb_hdobj[which(is.na(SQFdata_modif$sb_hdobj))] <- 'N'
SQFdata_modif$sb_outln[which(is.na(SQFdata_modif$sb_outln))] <- 'N'
SQFdata_modif$sb_admis[which(is.na(SQFdata_modif$sb_admis))] <- 'N'
SQFdata_modif$sb_other[which(is.na(SQFdata_modif$sb_other))] <- 'N'

# Comprobación de NAs
sum(is.na(SQFdata))
sum(is.na(SQFdata_modif))
```

### 3.3.4 Eliminación de variables con varianza nula

```{r}
# 
# Con caret::nearZeroVar se elimina el resto de variables que presentan varianza
# nula después de aplicar la imputación de NAs
#
SQFdata_modif <- SQFdata_modif[-nearZeroVar(SQFdata_modif)]

dim(SQFdata)
dim(SQFdata_modif)
```

## 5.1 Clustering variables numéricas

### 5.1.1 Separación de datos en categóricos y numéricos
```{r}
SQFdata_modif.num <- SQFdata_modif[,sapply(SQFdata_modif, is.numeric)]
str(SQFdata_modif.num)

# Creación de conjunto para clustering reducido
set.seed(123)
SQFdata_modif.num.red <- sample_n(SQFdata_modif.num, round(dim(SQFdata_modif.num)[1]/25))
```
```{r}
svm.train.radial <- svm(arstmade ~ . , SQFdata_modif[train, ], kernel = "radial", gamma = 1, cost = 100)
svm.test.radial <- predict(svm.train.radial, SQFdata_modif[train, ])
plot(svm.test.radial, SQFdata_modif[train, ])
summary(model)
table(svm.train.radial)
```
```{r}
train = sample(200, 200)
svm.train.linear <- svm(arstmade ~ . , SQFdata_modif[train, ], kernel = "linear", gamma = 1, cost = 100)
svm.test.linear<- predict(svm.train.linear, SQFdata_modif[train, ])
plot(svm.test.linear, SQFdata_modif[train, ])
summary(svm.train.linear)
table(svm.test.linear)

```

```{r}
train = sample(200, 200)
svm.train.polynomial <- svm(arstmade ~ . , SQFdata_modif[train, ], kernel = "polynomial", gamma = 1, cost = 100)
svm.test.polynomial<- predict(svm.train.polynomial, SQFdata_modif[train, ])
plot(svm.test.polynomial, SQFdata_modif[train, ])
summary(svm.train.polynomial)
table(svm.test.polynomial)
```
```{r}
train = sample(200, 200)
svm.train.sigmoid <- svm(arstmade ~ . , SQFdata_modif[train, ], kernel = "sigmoid", gamma = 1, cost = 100)
svm.test.sigmoid<- predict(svm.train.sigmoid, SQFdata_modif[train, ])
plot(svm.test.sigmoid, SQFdata_modif)
summary(svm.train.sigmoid)
table(svm.test.sigmoid)
```

